name: "Build"

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master]

jobs:
  build-project:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Create a certificate folder
        run: mkdir certs

      - name: Try to build the container
        run: docker build -t project .
