name: "Code Linter"

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master]

jobs:
  check-linter:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        version: [19]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install the prettier
        run: npm i -g prettier

      - name: Run the linter
        run: yarn run linter
